Repository valor-software/ngx-bootstrap, pull requests merged in 2018-11, with the labels that each got.

#4759 fix(build): back scss for datepicker
  scripts/build-modules.js
Labels: needs review

#4646 fix(pagination): fix tslint errors
  src/pagination/models/index.ts
  src/pagination/pager.component.ts
  src/pagination/pagination.component.ts
  src/pagination/pagination.config.ts
Labels: needs review

#4647 fix(positioning): fix tslint errors
  src/positioning/positioning.service.ts
Labels: needs review

#4648 fix(rating): fix tslint errors in src/rating component
  src/rating/models/index.ts
  src/rating/rating.component.html
  src/rating/rating.component.ts
Labels: needs review

#4649 fix(timepicker): fix tslint errors
  src/timepicker/models/index.ts
  src/timepicker/reducer/timepicker.reducer.ts
  src/timepicker/timepicker.component.ts
  src/timepicker/timepicker.utils.ts
Labels: needs review

#4650 fix(modal): fix tslint issues
  src/modal/bs-modal-ref.service.ts
  src/modal/bs-modal.service.ts
  src/modal/modal-container.component.ts
  src/modal/modal-options.class.ts
  src/modal/modal.directive.ts
  src/modal/models/index.ts
  tslint.json
Labels: needs review

#4656 fix(typeahead): fix tslint issues
  src/typeahead/typeahead-container.component.ts
  src/typeahead/typeahead-match.class.ts
  src/typeahead/typeahead-utils.ts
  src/typeahead/typeahead.directive.ts
Labels: needs review

#4643 fix(dropdown): fix tslint errors
  src/dropdown/bs-dropdown-container.component.ts
  src/dropdown/bs-dropdown-menu.directive.ts
  src/dropdown/bs-dropdown-toggle.directive.ts
  src/dropdown/bs-dropdown.directive.ts
  src/dropdown/bs-dropdown.module.ts
  src/dropdown/bs-dropdown.state.ts
Labels: needs review

#4639 fix(carousel): fix tslint errors
  src/carousel/carousel.component.ts
Labels: needs review

#4636 fix(buttons): fix tslint errors
  src/buttons/button-checkbox.directive.ts
  src/buttons/button-radio-group.directive.ts
  src/buttons/button-radio.directive.ts
Labels: needs review

#4663 fix(tests): e2e tests fixed and added different spec files
  cypress/integration/accordion_page_spec.ts
  cypress/integration/alerts_page_spec.ts
  cypress/integration/buttons_page_spec.ts
  cypress/integration/carousel_page_spec.ts
  cypress/integration/collapse_page_spec.ts
  cypress/integration/datepicker_page_spec.ts
  cypress/integration/demo_pages_spec.ts
  cypress/integration/dropdowns_page_spec.ts
  cypress/integration/each_page_loads_spec.ts
  cypress/integration/landing_page_spec.ts
  cypress/integration/modals_page_spec.ts
  cypress/integration/pagination_page_spec.ts
  cypress/integration/popover_page_spec.ts
  cypress/integration/progressbar_page_spec.ts
  cypress/integration/rating_page_spec.ts
  cypress/integration/sortable_page_spec.ts
  cypress/integration/tabs_page_spec.ts
  cypress/integration/timepicker_page_spec.ts
  cypress/integration/tooltip_page_spec.ts
  cypress/integration/typeahead_page_spec.ts
  package-lock.json
  package.json
Labels: ready for merge

#4733 feat(docs): add use-cases for dropdowns component
  docs/spec/dropdowns/dropdowns.examples.accessibility.use-case.md
  docs/spec/dropdowns/dropdowns.examples.append-to-body.use-case.md
  docs/spec/dropdowns/dropdowns.examples.auto-close.use-case.md
  docs/spec/dropdowns/dropdowns.examples.basic.use-case.md
  docs/spec/dropdowns/dropdowns.examples.config-defaults.use-case.md
  docs/spec/dropdowns/dropdowns.examples.custom-html.use-case.md
  docs/spec/dropdowns/dropdowns.examples.disabled-menu.use-case.md
  docs/spec/dropdowns/dropdowns.examples.dropup-variation.use-case.md
  docs/spec/dropdowns/dropdowns.examples.manual-trigger.md
  docs/spec/dropdowns/dropdowns.examples.mark-item-disabled.use-case.md
  docs/spec/dropdowns/dropdowns.examples.menu-alignment.use-case.md
  docs/spec/dropdowns/dropdowns.examples.menu-dividers.use-case.md
  docs/spec/dropdowns/dropdowns.examples.nested-dropdowns.use-case.md
  docs/spec/dropdowns/dropdowns.examples.split-button.use-case.md
  docs/spec/dropdowns/dropdowns.examples.state-change-event.use-case.md
  docs/spec/dropdowns/dropdowns.examples.trigger-by-a.use-case.md
  docs/spec/dropdowns/dropdowns.examples.trigger-by-isopen.use-case.md
  docs/spec/dropdowns/dropdowns.examples.visibility-events.use-case.md
  docs/spec/index.md
Labels: comp(dropdown), enhancement, needs review

#4696 feat(docs): typeahead-use-cases
  docs/spec/typeahead/typeahead.examples.append-to-body.use-case.md
  docs/spec/typeahead/typeahead.examples.async-data.use-case.md
  docs/spec/typeahead/typeahead.examples.basic-array.use-case.md
  docs/spec/typeahead/typeahead.examples.dropup.use-case.md
  docs/spec/typeahead/typeahead.examples.grouping-results.use-case.md
  docs/spec/typeahead/typeahead.examples.ignore-spaces-order.use-case.md
  docs/spec/typeahead/typeahead.examples.item-template.use-case.md
  docs/spec/typeahead/typeahead.examples.latinize.use-case.md
  docs/spec/typeahead/typeahead.examples.no-result.use-case.md
  docs/spec/typeahead/typeahead.examples.on-blur.use-case.md
  docs/spec/typeahead/typeahead.examples.on-select.use-case.md
  docs/spec/typeahead/typeahead.examples.option-field.use-case.md
  docs/spec/typeahead/typeahead.examples.phrase-delimiters.use-case.md
  docs/spec/typeahead/typeahead.examples.reactive-forms.use-case.md
  docs/spec/typeahead/typeahead.examples.scrollable.use-case.md
  docs/spec/typeahead/typeahead.examples.template-driven-forms.use-case.md
  docs/spec/typeahead/typeahead.examples.with-delay.use-case.md
Labels: comp(typeahead), needs review

#4778 fix(tests): cleanup test code
  .angular-cli.json.bak
  .travis.yml
  angular.json
  cypress/plugins/cy-ts-preprocessor.js
  cypress/plugins/index.js
  package-lock.json
  package.json
Labels: enhancement, needs review

#4785 fix(tests): karma conf update for sauce run
  .travis.yml
  karma-demo.conf.js
  package-lock.json
  package.json
Labels: enhancement, needs review

#4782 feat(docs): add summary for use-cases
  docs/spec/index.md
Labels: enhancement, needs review

#4800 fix(component-loader) back component-loader name of folder
  src/common/public_api.ts
  src/component-loader/package.json
  src/datepicker/bs-datepicker.component.ts
  src/datepicker/bs-datepicker.module.ts
  src/datepicker/bs-daterangepicker.component.ts
  src/dropdown/bs-dropdown.directive.ts
  src/dropdown/bs-dropdown.module.ts
  src/dropdown/bs-dropdown.state.ts
  src/modal/bs-modal.service.ts
  src/modal/modal.directive.ts
  src/modal/modal.module.ts
  src/popover/popover.directive.ts
  src/popover/popover.module.ts
  src/tooltip/tooltip.directive.ts
  src/tooltip/tooltip.module.ts
  src/typeahead/typeahead.directive.ts
  src/typeahead/typeahead.module.ts
Labels: comp(build), needs review, ready for merge

#4790 feat(build): disable inline source map
  package-lock.json
  scripts/build-modules.js
  scripts/ng-packagr/tsconfig.ngc.json
Labels: comp(build), needs review, ready for merge

#4634 feat(datepicker): add Norwegian locale
  demo/src/app/components/+datepicker/demo-datepicker.module.ts
  src/chronos/i18n/nb.ts
  src/chronos/public_api.ts
  src/chronos/test/locale/nb.spec.ts
  src/locale.ts
  src/locale/public_api.ts
Labels: comp(datepicker), feat(chronos), ready for merge

#4799 fix(build): add workaround for buildOptimizer issue
  angular.json
  src/chronos/format/format.ts
  src/chronos/locale/locales.ts
  src/chronos/public_api.ts
  src/chronos/units/day-of-month.ts
  src/chronos/units/day-of-week.ts
  src/chronos/units/day-of-year.ts
  src/chronos/units/hour.ts
  src/chronos/units/millisecond.ts
  src/chronos/units/minute.ts
  src/chronos/units/month.ts
  src/chronos/units/offset.ts
  src/chronos/units/quarter.ts
  src/chronos/units/second.ts
  src/chronos/units/timestamp.ts
  src/chronos/units/timezone.ts
  src/chronos/units/week-year.ts
  src/chronos/units/week.ts
  src/chronos/units/year.ts
Labels: comp(build), ready for merge

#4599 feat(datepicker): add bulgarian locale
  demo/src/app/components/+datepicker/demo-datepicker.module.ts
  src/chronos/i18n/bg.ts
  src/chronos/test/locale/bg.spec.ts
  src/locale.ts
Labels: comp(datepicker), needs review

#4700 feat(docs): add use-cases for datepicker component
  docs/spec/datepicker/datepicker.examples.basic.use-case.md
  docs/spec/datepicker/datepicker.examples.config-method.use-case.md
  docs/spec/datepicker/datepicker.examples.config-properties.md
  docs/spec/datepicker/datepicker.examples.custom-date-format.use-case.md
  docs/spec/datepicker/datepicker.examples.custom-trigger.md
  docs/spec/datepicker/datepicker.examples.disabled.use-case.md
  docs/spec/datepicker/datepicker.examples.forms.use-case.md
  docs/spec/datepicker/datepicker.examples.hide-on-scroll.use-case.md
  docs/spec/datepicker/datepicker.examples.initial-state.use-case.md
  docs/spec/datepicker/datepicker.examples.locales.use-case.md
  docs/spec/datepicker/datepicker.examples.manual-trigger.use-case.md
  docs/spec/datepicker/datepicker.examples.min-max.use-case.md
  docs/spec/datepicker/datepicker.examples.outside-click.md
  docs/spec/datepicker/datepicker.examples.placement.use-case.md
  docs/spec/datepicker/datepicker.examples.reactive-forms.use-case.md
  docs/spec/datepicker/datepicker.examples.themes.use-case.md
  docs/spec/datepicker/datepicker.examples.trigger-by-isopen.md
  docs/spec/datepicker/datepicker.examples.value-change-event.use-case.md
  docs/spec/datepicker/datepicker.examples.visibility-events.use-case.md
  docs/spec/index.md
Labels: comp(datepicker), enhancement, ready for merge

#4813 fix(travis): fix tslint stage
  .travis.yml
Labels: needs review

#4748 Feat docs use cases tooltip
  docs/spec/tooltip/tooltip.examles.placement.use-case.md
  docs/spec/tooltip/tooltip.examples.append-to-body.use-case.md
  docs/spec/tooltip/tooltip.examples.basic.use-case.md
  docs/spec/tooltip/tooltip.examples.comp-level-styling.use-case.md
  docs/spec/tooltip/tooltip.examples.config-defaults.use-case.md
  docs/spec/tooltip/tooltip.examples.custom-class.use-case.md
  docs/spec/tooltip/tooltip.examples.custom-content-template.use-case.md
  docs/spec/tooltip/tooltip.examples.custom-triggers.use-case.md
  docs/spec/tooltip/tooltip.examples.dimiss-on-next-click.use-case.md
  docs/spec/tooltip/tooltip.examples.dynamic-content.use-case.md
  docs/spec/tooltip/tooltip.examples.dynamic-html.use-case.md
  docs/spec/tooltip/tooltip.examples.manual-trigger.use-case.md
  docs/spec/tooltip/tooltip.examples.tooltip-with-delay.use-case.md
Labels: comp(tooltip), enhancement, ready for merge

#4820 fix(travis): fix heroku stage
  .travis.yml
  angular.json
  package-lock.json
  package.json
  scripts/universal/prerender.ts
  scripts/universal/server.ts
  scripts/universal/webpack.server.config.js
Labels: needs review, ready for merge

#4812 feat(datepicker) add bulgarian locale
  demo/src/app/components/+datepicker/demo-datepicker.module.ts
  schematics/src/ng-add/index.ts
  src/chronos/i18n/bg.ts
  src/chronos/public_api.ts
  src/chronos/test/locale/bg.spec.ts
  src/locale.ts
  src/locale/public_api.ts
Labels: comp(datepicker), ready for merge

#4859 fix(components-spec): fix paths in spec.ts files
  src/spec/accordion.component.spec.ts
  src/spec/alert.component.spec.ts
  src/spec/bs-dropdown.directive.spec.ts
  src/spec/button.directive.spec.ts
  src/spec/carousel.component.spec.ts
  src/spec/collapse.directive.spec.ts
  src/spec/draggable-item.service.spec.ts
  src/spec/ng-bootstrap/alert.spec.ts
  src/spec/ng-bootstrap/carousel.spec.ts
  src/spec/ng-bootstrap/collapse.spec.ts
  src/spec/ng-bootstrap/popover.spec.ts
  src/spec/ng-bootstrap/tooltip.spec.ts
  src/spec/ng-bootstrap/utils/triggers.spec.ts
  src/spec/pager.component.spec.ts
  src/spec/pagination.component.spec.ts
  src/spec/progressbar.component.spec.ts
  src/spec/rating.component.spec.ts
  src/spec/sortable.component.spec.ts
  src/spec/tabset.component.spec.ts
  src/spec/timepicker/timepicker.component.spec.ts
  src/spec/tooltip.directive.spec.ts
  src/spec/typeahead-container.component.spec.ts
  src/spec/typeahead.directive.spec.ts
Labels: ready for merge
