Repository valor-software/ngx-bootstrap, pull requests merged in 2018-06, with the labels that each got.

#4420 fix: remove peer dependency on @angular/forms
  src/package.json
Labels: needs review

#4328 fix browser rounding width/height bug in ng-position
  src/positioning/ng-positioning.ts
Labels: prio: high, ready for tests

#4391 feat(datepicker): Slovak locale added to chronos
  demo/src/app/components/+datepicker/demo-datepicker.module.ts
  src/chronos/i18n/sk.ts
  src/chronos/test/locale/sk.spec.ts
  src/locale.ts
Labels: needs review, prio: low

#4170 docs(tabs): add aria attributes description
  demo/src/app/components/+tabs/demos/accessibility/accessibility.html
Labels: prio: low

#4167 docs(sortable): add aria attributes description
  demo/src/app/components/+sortable/demos/accessibility/accessibility.html
  demo/src/app/components/+sortable/demos/accessibility/accessibility.ts
  demo/src/app/components/+sortable/demos/index.ts
  demo/src/app/components/+sortable/sortable-section.list.ts
Labels: prio: medium

#4455 refactor: Capitalize pt-br's locale month names
  src/chronos/i18n/pt-br.ts
  src/chronos/test/locale/pt-br.spec.ts
Labels: effort1: easy (hours), feat(chronos), needs fix, needs review
