Repository valor-software/ngx-bootstrap, pull requests merged in 2019-07, with the labels that each got.

#5316 fix(collapse): fix collapse animation (child height)
  cypress/support/accordion.po.ts
  demo/src/app/components/+accordion/docs/usage.md
  demo/src/app/components/+collapse/docs/usage.md
  demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts
  demo/src/app/docs/demo-section-components/demo-examples-section/stackblitz/polyfills.ts
  demo/src/polyfills.ts
  package-lock.json
  package.json
  src/collapse/collapse.directive.ts
Labels: comp(accordion), comp(collapse), ready for merge

#5318 fix(tests): add hard fix for cy test with animation
  cypress/support/accordion.po.ts
Labels: enhancement

#5337 feat(build): update to latest angular(8.1.2)
  package-lock.json
  package.json
  src/datepicker/bs-datepicker.module.ts
Labels: comp(build), ready for merge
