Repository valor-software/ngx-bootstrap, pull requests merged in 2019-03, with the labels that each got.

#5065 feat(positioning): update variation behavior and add adaptive option
  cypress/full/datepicker/placement_spec.ts
  demo/src/app/components/+datepicker/datepicker-section.list.ts
  demo/src/app/components/+datepicker/demos/adaptive-position/adaptive-position.html
  demo/src/app/components/+datepicker/demos/adaptive-position/adaptive-position.ts
  demo/src/app/components/+datepicker/demos/index.ts
  demo/src/app/components/+typeahead/demos/adaptive-position/adaptive-position.html
  demo/src/app/components/+typeahead/demos/adaptive-position/adaptive-position.ts
  demo/src/app/components/+typeahead/demos/index.ts
  demo/src/app/components/+typeahead/typeahead-section.list.ts
  demo/src/ng-api-doc.ts
  src/datepicker/bs-datepicker.config.ts
  src/datepicker/themes/bs/bs-datepicker-container.component.ts
  src/datepicker/themes/bs/bs-datepicker-inline-container.component.ts
  src/datepicker/themes/bs/bs-daterangepicker-container.component.ts
  src/popover/popover.directive.ts
  src/positioning/models/index.ts
  src/positioning/modifiers/flip.ts
  src/positioning/modifiers/initData.ts
  src/positioning/ng-positioning.ts
  src/positioning/positioning.service.ts
  src/positioning/utils/computeAutoPlacement.ts
  src/positioning/utils/index.ts
  src/positioning/utils/isModifierEnabled.ts
  src/tooltip/tooltip.directive.ts
  src/typeahead/typeahead.config.ts
  src/typeahead/typeahead.directive.ts
Labels: comp(datepicker), comp(positioning), comp(typeahead), ready for merge

#5072 tests(sortable): add full e2e covegare for Sortable component
  cypress/full/sortable_page_spec.ts
  cypress/integration/sortable_page_spec.ts
  cypress/support/sortable.po.ts
  demo/src/app/components/+sortable/demos/basic/basic.component.html
  demo/src/app/components/+sortable/demos/complex-datamodel/complex-datamodel.component.html
  demo/src/app/components/+sortable/demos/custom-item-template/custom-item-template.html
  docs/spec/sortable/sortable.examples.complex-data-model.use-case.md
Labels: comp(sortable), enhancement, needs review

#5067 tests(rating): add full e2e coverage for Rating component
  cypress/full/rating_page_spec.ts
  cypress/integration/rating_page_spec.ts
  cypress/support/base.component.ts
  cypress/support/rating.po.ts
  demo/src/app/components/+rating/demos/custom/custom.html
  docs/spec/rating/rating.examples.dynamic.use-case.md
Labels: comp(rating), needs review

#5062 tests(dropdown): add full e2e coverage for dropdown component
  cypress/full/dropdowns_page_spec.ts
  cypress/integration/dropdowns_page_spec.ts
  cypress/support/base.component.ts
  cypress/support/dropdowns.po.ts
  demo/src/app/components/+dropdown/demos/nested-dropdowns/nested-dropdowns.html
  demo/src/app/components/+dropdown/dropdown-section.list.ts
  docs/spec/dropdowns/dropdowns.examples.inside-click.use-case.md
  docs/spec/dropdowns/dropdowns.examples.nested-dropdowns.use-case.md
  docs/spec/index.md
Labels: comp(dropdown), enhancement, needs review

#5073 fix(build): fix window not defined on An Universal
  src/positioning/positioning.service.ts
Labels: comp(positioning), ready for merge

#5083 WIP ci(travis): update process
  .travis.yml
  package.json
  scripts/ci/copy-to-ngx-pkg.js
  scripts/ci/update-pkg.js
Labels: WIP, needs review

#5078 fix(timepicker): min-max demo fix, closes(#5053)
  src/timepicker/timepicker.utils.ts
Labels: comp(timepicker), ready for merge

#5063 tests(common): snapshot visual tests with applitools
  .travis.yml
  cypress/plugins/index.js
  cypress/snapshot/snapshot_spec.js
  cypress/support/index.js
  cypress/tsconfig.json
  package-lock.json
  package.json
Labels: enhancement, needs review

#5081 fix(modal): fix anchor for esc closing option demo
  demo/src/app/components/+modal/modal-section.list.ts
Labels: comp(modal), ready for merge

#5050 feat(test): add e2e tests for typeahead component
  cypress/full/typeahead_page_spec.ts
  cypress/integration/typeahead_page_spec.ts
  cypress/support/base.component.ts
  cypress/support/typeahead.po.ts
  docs/spec/typeahead/typeahead.examples.append-to-body.use-case.md
  docs/spec/typeahead/typeahead.examples.async-data.use-case.md
  docs/spec/typeahead/typeahead.examples.basic-array.use-case.md
  docs/spec/typeahead/typeahead.examples.configuring-defaults.use-case.md
  docs/spec/typeahead/typeahead.examples.dropup.use-case.md
  docs/spec/typeahead/typeahead.examples.grouping-results.use-case.md
  docs/spec/typeahead/typeahead.examples.ignore-spaces-order.use-case.md
  docs/spec/typeahead/typeahead.examples.item-template.use-case.md
  docs/spec/typeahead/typeahead.examples.latinize.use-case.md
  docs/spec/typeahead/typeahead.examples.no-result.use-case.md
  docs/spec/typeahead/typeahead.examples.on-blur.use-case.md
  docs/spec/typeahead/typeahead.examples.on-select.use-case.md
  docs/spec/typeahead/typeahead.examples.option-field.use-case.md
  docs/spec/typeahead/typeahead.examples.phrase-delimiters.use-case.md
  docs/spec/typeahead/typeahead.examples.reactive-forms.use-case.md
  docs/spec/typeahead/typeahead.examples.scrollable.use-case.md
  docs/spec/typeahead/typeahead.examples.selected-first-item.use-case.md
  docs/spec/typeahead/typeahead.examples.show-on-blur.md
  docs/spec/typeahead/typeahead.examples.template-driven-forms.use-case.md
  docs/spec/typeahead/typeahead.examples.with-delay.use-case.md
Labels: comp(typeahead), ready for merge

#5108 fix(tests): fix cy all command
  package.json
Labels: enhancement, needs review

#5098 tests(common): fix configuration for unit tests, coverage
  angular.json
  karma-demo.conf.js
  scripts/sauce-browsers.js
Labels: enhancement, needs review

#5109 fix(tests): select week datepicker fix
  cypress/full/datepicker/select_week_spec.ts
Labels: enhancement, needs review

#5069 refactor(common): migrate to angular 7
  .travis.yml
  package-lock.json
  package.json
  schematics/src/ng-add/index.ts
  scripts/ci/npm-ng-latest.sh
  scripts/ci/npm-ng-min.sh
  scripts/ci/npm-ng-next.sh
  scripts/ci/update-pkg.js
  src/chronos/i18n/lt.ts
  src/chronos/utils/type-checks.ts
  src/locale.ts
  src/pagination/pager.component.ts
  src/pagination/pagination.component.ts
  src/positioning/modifiers/arrow.ts
  src/positioning/modifiers/preventOverflow.ts
  src/positioning/modifiers/shift.ts
  src/positioning/utils/getBordersSize.ts
  src/positioning/utils/getOppositePlacement.ts
  src/positioning/utils/getStyleComputedProperty.ts
  src/positioning/utils/getTargetOffsets.ts
  src/positioning/utils/getWindowSizes.ts
  src/timepicker/models/index.ts
Labels: enhancement, ready for merge

#5092 test(common): update all tests according to the common approach
  cypress/full/carousel_page_spec.ts
  cypress/integration/carousel_page_spec.ts
  cypress/integration/each_page_loads_spec.ts
  cypress/integration/landing_page_spec.ts
  cypress/support/base.component.ts
  cypress/support/landing.po.ts
Labels: enhancement, needs review

#5111 fix(travis): fix travis development
  .travis.yml
Labels: ready for merge

#5002 fix(tabs): fix an invoke of select event outside of tabs (#3755)
  .travis.yml
  demo/src/app/components/+tabs/demos/dynamic/dynamic.html
  demo/src/app/components/+tabs/demos/select-event/select-event.html
  demo/src/ng-api-doc.ts
  src/spec/tabset.component.spec.ts
  src/tabs/tab.directive.ts
Labels: BREAKING CHANGE, comp(tabs), ready for merge

#5115 fix(tavis): fix travis next stage and unpublish ngx-bootstrap-ci
  .travis.yml
  scripts/ci/npm-ng-next.sh
Labels: ready for tests

#5116 fix(travis): fix travis on fork
  .travis.yml
Labels: ready for tests

#5066 test(core): e2e for modal component
  cypress/full/modals_directive_page.spec.ts
  cypress/full/modals_service_page_spec.ts
  cypress/integration/modals_page_spec.ts
  cypress/support/base.component.ts
  cypress/support/modals.po.ts
  docs/spec/modals/modals.service-examples.animation-option.use-case.md
  docs/spec/modals/modals.service-examples.component.use-case.md
  docs/spec/modals/modals.service-examples.template.use-case.md
Labels: comp(modal), ready for merge

#5119 fix(positioning): fix frozen page
  package.json
  src/positioning/utils/getOffsetParent.ts
Labels: comp(positioning), ready for merge

#5122 fix(travis): fix Tarvis on release
  .travis.yml
Labels: ready for merge

#5124 fix(tests): remove applitools logs
  package.json
Labels: enhancement, needs review

#5117 test(timepicker): add e2e coverage for Timepicker component
  cypress/full/timepicker/arrow_keys_spec.ts
  cypress/full/timepicker/configuring_defaults_spec.ts
  cypress/full/timepicker/custom_validation_events_spec.ts
  cypress/full/timepicker/custom_validation_spec.ts
  cypress/full/timepicker/dynamic_spec.ts
  cypress/full/timepicker/form_spec.ts
  cypress/full/timepicker/mouse_wheel_spec.ts
  cypress/full/timepicker/spinners_spec.ts
  cypress/integration/timepicker_page_spec.ts
  cypress/support/timepicker.po.ts
  docs/spec/timepicker/timepicker.examples.arrow-keys.use-case.md
  docs/spec/timepicker/timepicker.examples.basic.use-case.md
  docs/spec/timepicker/timepicker.examples.config-defaults.use-case.md
  docs/spec/timepicker/timepicker.examples.custom-meridian.use-case.md
  docs/spec/timepicker/timepicker.examples.custom-steps.use-case.md
  docs/spec/timepicker/timepicker.examples.custom-validation-event.use-case.md
  docs/spec/timepicker/timepicker.examples.custom-validation.use-case.md
  docs/spec/timepicker/timepicker.examples.disabled.use-case.md
  docs/spec/timepicker/timepicker.examples.dynamic.use-case.md
  docs/spec/timepicker/timepicker.examples.form.use-case.md
  docs/spec/timepicker/timepicker.examples.meridian.use-case.md
  docs/spec/timepicker/timepicker.examples.min-max.use-case.md
  docs/spec/timepicker/timepicker.examples.mouse-wheel.use-case.md
  docs/spec/timepicker/timepicker.examples.readonly.use-case.md
  docs/spec/timepicker/timepicker.examples.spinners.use-case.md
  docs/spec/timepicker/timepicker.examples.toggle-min-sec.use-case.md
Labels: comp(timepicker), needs review

#5123 fix(build): fix fail on target=es6
  package.json
  scripts/es2015/bundle.es2015.js
  scripts/es2015/es2015.config.js
  scripts/es2015/rollup.globals.js
  src/package.json
Labels: comp(build), ready for merge

#5131 fix(common): fix peer dependencies
  package.json
  scripts/ci/npm-ng-next.sh
Labels: needs review
