Repository valor-software/ngx-bootstrap, pull requests merged in 2019-04, with the labels that each got.

#3983 feat(typeahead) stop selecting first result when displaying matches
  demo/src/app/components/+typeahead/demos/first-item-active/first-item-active.html
  demo/src/app/components/+typeahead/demos/first-item-active/first-item-active.ts
  demo/src/app/components/+typeahead/demos/index.ts
  demo/src/app/components/+typeahead/demos/min-length/min-length.html
  demo/src/app/components/+typeahead/demos/min-length/min-length.ts
  demo/src/app/components/+typeahead/typeahead-section.list.ts
  demo/src/ng-api-doc.ts
  src/spec/typeahead-container.component.spec.ts
  src/typeahead/typeahead-container.component.ts
  src/typeahead/typeahead.config.ts
  src/typeahead/typeahead.directive.ts
Labels: comp(typeahead), prio: medium, ready for merge

#5091 tests(timepicker): add full e2e coverage for 50% demos of Timepicker
  cypress/full/datepicker/min_max_spec.ts
  cypress/full/timepicker/arrow_keys_spec.ts
  cypress/full/timepicker/configuring_defaults_spec.ts
  cypress/full/timepicker/custom_meridian_spec.ts
  cypress/full/timepicker/custom_steps_spec.ts
  cypress/full/timepicker/custom_validation_events_spec.ts
  cypress/full/timepicker/custom_validation_spec.ts
  cypress/full/timepicker/disabled_spec.ts
  cypress/full/timepicker/dynamic_spec.ts
  cypress/full/timepicker/form_spec.ts
  cypress/full/timepicker/meridian_spec.ts
  cypress/full/timepicker/min_max_spec.ts
  cypress/full/timepicker/mouse_wheel_spec.ts
  cypress/full/timepicker/readonly_spec.ts
  cypress/full/timepicker/spinners_spec.ts
  cypress/full/timepicker/toggle_min_sec_spec.ts
  cypress/integration/timepicker_page_spec.ts
  cypress/support/base.component.ts
  cypress/support/timepicker.po.ts
  docs/spec/timepicker/timepicker.examples.arrow-keys.use-case.md
  docs/spec/timepicker/timepicker.examples.basic.use-case.md
  docs/spec/timepicker/timepicker.examples.config-defaults.use-case.md
  docs/spec/timepicker/timepicker.examples.custom-meridian.use-case.md
  docs/spec/timepicker/timepicker.examples.custom-steps.use-case.md
  docs/spec/timepicker/timepicker.examples.custom-validation-event.use-case.md
  docs/spec/timepicker/timepicker.examples.custom-validation.use-case.md
  docs/spec/timepicker/timepicker.examples.disabled.use-case.md
  docs/spec/timepicker/timepicker.examples.dynamic.use-case.md
  docs/spec/timepicker/timepicker.examples.form.use-case.md
  docs/spec/timepicker/timepicker.examples.meridian.use-case.md
  docs/spec/timepicker/timepicker.examples.min-max.use-case.md
  docs/spec/timepicker/timepicker.examples.mouse-wheel.use-case.md
  docs/spec/timepicker/timepicker.examples.readonly.use-case.md
  docs/spec/timepicker/timepicker.examples.spinners.use-case.md
  docs/spec/timepicker/timepicker.examples.toggle-min-sec.use-case.md
Labels: comp(timepicker), enhancement, needs review

#5139 fix(tests): remove 3d cypress thread, unnecessary
  .travis.yml
Labels: enhancement, needs review

#5142 fix(tests): fix cypress datepicker tests in development
  cypress/full/datepicker/min_max_spec.ts
  cypress/full/datepicker/select_week_spec.ts
  cypress/support/datepicker.po.ts
Labels: enhancement, needs review

#4605 perf(dropdown): reduce the number of document click listeners
  src/dropdown/bs-dropdown-toggle.directive.ts
Labels: comp(dropdown), ready for merge

#5145 fix(tests): modal e2e tests fix, cypress update
  cypress/full/modals_directive_page_spec.ts
  cypress/full/modals_service_page_spec.ts
  cypress/support/modals.po.ts
  package-lock.json
  package.json
Labels: enhancement, needs review

#5143 WIP feat(support): add info about supporting and donate
  README.md
  demo/src/app/common/documentation/documentation.component.html
  demo/src/app/common/landing/landing.component.html
  demo/src/assets/css/style.scss
Labels: enhancement, needs review

#5152 feat(build): express to nestjs in ssr
  .travis.yml
  demo/src/app/common/top-menu/top-menu.component.ts
  package-lock.json
  package.json
  scripts/universal/app.module.ts
  scripts/universal/prerender.ts
  scripts/universal/server.ts
  scripts/universal/webpack.server.config.js
  src/positioning/utils/isIE.ts
  tsconfig.json
Labels: needs review

#5156 feat(build): update nestjs-universal config
  demo/src/assets/json/current-version.json
  package-lock.json
  package.json
  scripts/universal/app.module.ts
  scripts/universal/configure-heroku.js
  scripts/universal/server.ts
Labels: needs review

#5157 fix(tests): add fixes for timepicker tests stability
  cypress/full/timepicker/arrow_keys_spec.ts
  cypress/full/timepicker/custom_steps_spec.ts
  cypress/full/timepicker/disabled_spec.ts
  cypress/full/timepicker/form_spec.ts
  cypress/full/timepicker/meridian_spec.ts
  cypress/full/timepicker/min_max_spec.ts
  cypress/integration/timepicker_page_spec.ts
  cypress/support/timepicker.po.ts
Labels: enhancement, needs review

#5160 fix(tests): stabilize spinners timepicker test
  cypress/full/timepicker/custom_validation_events_spec.ts
  cypress/full/timepicker/spinners_spec.ts
Labels: enhancement, needs review

#5161 fix(tests): enhancements to group and key params for cypress
  .travis.yml
Labels: enhancement, needs review

#5134 ET Locale for DatePicker
  demo/src/app/components/+datepicker/demo-datepicker.module.ts
  src/chronos/i18n/et.ts
  src/chronos/public_api.ts
  src/chronos/test/locale/et.spec.ts
  src/locale.ts
  src/locale/public_api.ts
Labels: comp(datepicker)

#5169 fix(build): fix build on Angular next
  scripts/ci/npm-ng-next.sh
Labels: needs review

#5171 fix(ci): fix travis deploy on surge
  .travis.yml
Labels: needs review

#4098 feat(demo): add stackblitz examples via SDK
  demo/src/app/app.routing.ts
  demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.html
  demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts
  demo/src/app/docs/demo-section-components/demo-examples-section/stackblitz/app.module.ts
  demo/src/app/docs/demo-section-components/demo-examples-section/stackblitz/helpers.ts
  demo/src/app/docs/demo-section-components/demo-examples-section/stackblitz/html.ts
  demo/src/app/docs/demo-section-components/demo-examples-section/stackblitz/main.ts
  demo/src/app/docs/demo-section-components/demo-examples-section/stackblitz/polyfills.ts
  demo/src/assets/images/stackblitz.png
  package-lock.json
  package.json
Labels: comp(demo), needs review, prio: medium

#5133 feat(carousel): allow to display multiple items per one slide
  demo/src/app/components/+carousel/carousel-section.component.ts
  demo/src/app/components/+carousel/carousel-section.list.ts
  demo/src/app/components/+carousel/demos/index.ts
  demo/src/app/components/+carousel/demos/multilist-from-index/multilist-from-index.html
  demo/src/app/components/+carousel/demos/multilist-from-index/multilist-from-index.ts
  demo/src/app/components/+carousel/demos/multilist-single-offset/multilist-single-offset.html
  demo/src/app/components/+carousel/demos/multilist-single-offset/multilist-single-offset.ts
  demo/src/app/components/+carousel/demos/multilist/multilist.html
  demo/src/app/components/+carousel/demos/multilist/multilist.ts
  demo/src/app/docs/api-docs/sample-box/sample-box.component.ts
  demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts
  demo/src/app/docs/demo-section-components/demo-top-section/demo-top-section.component.ts
  demo/src/app/docs/docs-section/docs-section.component.ts
  demo/src/polyfills.ts
  src/carousel/carousel.component.html
  src/carousel/carousel.component.ts
  src/carousel/carousel.config.ts
  src/carousel/models/index.ts
  src/carousel/slide.component.ts
  src/carousel/utils.ts
  src/spec/carousel.component.spec.ts
  src/spec/ng-bootstrap/carousel.spec.ts
Labels: comp(carousel)

#5176 fix(stackblitz): add carousel correct links, datepicker locales
  cypress/full/datepicker/min_max_spec.ts
  demo/src/app/components/+accordion/accordion-section.list.ts
  demo/src/app/components/+accordion/demos/styling/styling.css
  demo/src/app/components/+accordion/demos/styling/styling.ts
  demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.html
  demo/src/app/docs/demo-section-components/demo-examples-section/examples.component.ts
  demo/src/app/docs/demo-section-components/demo-examples-section/stackblitz/app.module.ts
Labels: enhancement, needs review

#4556 updated file name of angular cli config file
  docs/getting-started/bootstrap.md
Labels: enhancement, needs review

#5177 fix(ci): fix build next
  scripts/ci/npm-ng-next.sh
Labels: comp(build), needs review

#5179 fix(ci): fix check prod build on next
  scripts/ci/npm-ng-next.sh
Labels: needs review

#4674 style(datepicker): change Thai 'weekdaysShort' format for look better…
  src/chronos/i18n/th.ts
  src/chronos/test/locale/th.spec.ts
Labels: comp(datepicker), ready for merge

#5174 feat(loader): container attribute implementation
  demo/src/app/components/+typeahead/typeahead-section.list.ts
  demo/src/ng-api-doc.ts
  src/component-loader/component-loader.class.ts
  src/datepicker/bs-datepicker.component.ts
  src/datepicker/bs-daterangepicker.component.ts
  src/dropdown/bs-dropdown.directive.ts
  src/popover/popover.config.ts
  src/popover/popover.directive.ts
  src/tooltip/tooltip.config.ts
  src/tooltip/tooltip.directive.ts
  src/typeahead/typeahead.directive.ts
Labels: comp(loader), ready for merge

#4512 docs(@angular/cli) update angular.json config file
  docs/getting-started/ng-cli.md
Labels: needs review

#5182 fix(tests): remove deprecated Init event (closes #5005)
  scripts/helpers.ts
Labels: enhancement, needs review
